import Toybox.Lang;
import Toybox.Test;
import Toybox.System;
import Toybox.Application;
import Toybox.Application.Storage;
import Toybox.WatchUi;

//! End-to-end checks that run inside the Connect IQ simulator, driven by
//! `scripts/simulator-test.sh`. Each is a seed fixture, a real app run, and a verify fixture;
//! simulator storage persists between invocations, which is what makes the split work.
//!
//! The unit suite cannot cover any of this. Generation runs a slice per timer tick and
//! `makeImageRequest` only completes on the event loop, neither of which a synchronous test
//! function ever reaches.
//!
//! Two paths, and they are mutually exclusive — `AppView.onCodesChanged` only queues downloads
//! when `CodeGeneration.enabled()` is false:
//!
//!   * generation (`integrationSeed` / `integrationVerify`) is what ships and what the default
//!     settings select. The app builds each code on the watch and touches no network.
//!   * download (`integrationSeedDownloadFallback` / `integrationVerifyDownload`) is the
//!     fallback kept for one release. It needs the code service to answer Garmin's image proxy,
//!     which it does not reliably do (CIQQA-3382), so the script only runs it on request.
//!
//! Seeding the generation path and then asserting a downloaded image, as this file did between
//! 1716b25 and now, fails every time and says nothing about either path.
//!
//! These live in `integration/`, which only `monkey-integration.jungle` compiles, so they never
//! run as part of the normal unit suite.

const SEED_QR_TEXT = "https://example.com/pass?id=42&type=member";  // the `&` is the point
const SEED_QR_TITLE = "Ampersand QR";
const SEED_BARCODE_TEXT = "MEMBER 12345";                          // the space is the point
const SEED_BARCODE_TITLE = "Gym card";

(:test)
function integrationSeed(logger as Test.Logger) as Boolean {
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue("pendingImageSlots");
    Storage.deleteValue(CodeStore.GLANCE_IMAGE);
    Application.Properties.setValue(
        CodeStore.PROP_CODES, [] as Array<Application.PropertyValueType>);
    // Match a real install. The simulator persists properties between runs, so without this the
    // fixture inherits whatever the last unit-test run left behind -- and the unit tests turn
    // generation off, which quietly puts the app back on the dead download path.
    Application.Properties.setValue(CodeGeneration.SETTING, true);

    CodeStore.save(0, $.SEED_QR_TITLE, $.SEED_QR_TEXT, CodeStore.TYPE_QR);
    CodeStore.save(1, $.SEED_BARCODE_TITLE, $.SEED_BARCODE_TEXT, CodeStore.TYPE_BARCODE);
    CodeStore.publishProperties();

    Test.assertEqualMessage(CodeStore.count(), 2, "two codes seeded");
    Test.assertMessage(!CodeStore.isCacheValid(0), "slot 0 starts with no image");
    Test.assertMessage(!CodeStore.isCacheValid(1), "slot 1 starts with no image");
    Test.assertMessage(!CodeStore.isGeneratedValid(0), "slot 0 starts with nothing generated");
    Test.assertMessage(CodeGeneration.enabled(), "codes are generated on the watch, as shipped");

    logger.debug("SEEDED 2 codes, nothing cached and nothing generated");
    return true;
}

//! The app builds the visible code on the watch, caches it, and never reaches for the network.
//!
//! Only slot 0 is generated by a plain boot: `AppView.loadCurrent` builds the code on screen and
//! `prepareGlanceCode` builds the one the glance draws, which is the same slot here. Slot 1 is
//! built when the user navigates to it, which this cannot drive.
(:test)
function integrationVerify(logger as Test.Logger) as Boolean {
    Test.assertMessage(CodeStore.isGeneratedValid(0),
        "slot 0 has no generated code after running the app — generation never completed");

    // Attribution: what was cached was built from the text in the slot, so a build cannot have
    // landed on the wrong one. Assert presence before calling equals, or a missing key throws
    // and the test reports an exception instead of the failure it describes.
    var meta = Storage.getValue(CodeStore.generatedMetaTextKey(0));
    Test.assertMessage(meta instanceof String, "the generated code has metadata");
    Test.assertMessage(meta.equals($.SEED_QR_TEXT), "it is attributed to slot 0's text");

    // A QR, not a barcode: the matrix loads back and is a legal QR square. Versions are
    // 21 to 177 modules in steps of 4, so a wrong shape or a truncated ByteArray fails here.
    var matrix = CodeStore.cachedMatrix(0);
    Test.assertMessage(matrix != null, "the matrix loads back out of storage");
    logger.debug("QR matrix " + matrix.size + "x" + matrix.size);
    Test.assertMessage(matrix.size >= 21 && matrix.size <= 177 && (matrix.size - 21) % 4 == 0,
        "not a legal QR size: " + matrix.size);
    Test.assertMessage(CodeStore.cachedBars(0) == null, "a QR code has no bars");

    // The whole point of generating locally: no request was made, so none of the image-proxy
    // failures can apply. A queued slot would mean the app fell back to the service.
    Test.assertMessage(Storage.getValue(CodeStore.imageKey(0)) == null,
        "nothing was downloaded for slot 0");
    var persisted = Storage.getValue(CodeStore.PENDING_SLOTS);
    Test.assertMessage(persisted == null || (persisted as Array).size() == 0,
        "the download queue stayed empty");

    logger.debug("VERIFIED the code was generated on the watch, with no network request");
    return true;
}

//! Run after a *second* app run: the cache survives a restart. This is the check for the defect
//! that made every load throw the cache away, and for the glance being able to draw at all —
//! `GlanceView` reads these caches and cannot build a code itself.
//!
//! Whether the second run rebuilt the code is not observable from storage: encoding is
//! deterministic, so a rebuild writes the same bytes. What is observable, and what actually
//! broke before, is whether anything is still there afterwards.
(:test)
function integrationVerifyWarmStart(logger as Test.Logger) as Boolean {
    Test.assertMessage(CodeStore.isGeneratedValid(0),
        "the generated code did not survive a restart — something discarded the cache");

    var matrix = CodeStore.cachedMatrix(0);
    Test.assertMessage(matrix != null, "the glance still has a matrix to draw");
    logger.debug("QR matrix still " + matrix.size + "x" + matrix.size + " after a restart");

    // Still no network. Nothing in the generation path enqueues: `AppView.onCodesChanged` only
    // calls `enqueueAll` when generation is off, and `GlanceView` only reads caches.
    var persisted = Storage.getValue(CodeStore.PENDING_SLOTS);
    Test.assertMessage(persisted == null || (persisted as Array).size() == 0,
        "a warm start queued a download");

    logger.debug("VERIFIED the cache survived a restart, with no network request");
    return true;
}

// ------------------------------------------------------- download fallback

//! The service path, kept for one release for payloads the local encoders cannot handle. Run
//! with `WITH_DOWNLOAD=1 ./scripts/simulator-test.sh`; it needs the code service to answer
//! Garmin's image proxy, which is outside this repo's control.
(:test)
function integrationSeedDownloadFallback(logger as Test.Logger) as Boolean {
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue(CodeStore.PENDING_SLOTS);
    Storage.deleteValue(CodeStore.GLANCE_IMAGE);
    Application.Properties.setValue(
        CodeStore.PROP_CODES, [] as Array<Application.PropertyValueType>);
    // The point of this fixture: the service, not the local encoders.
    Application.Properties.setValue(CodeGeneration.SETTING, false);

    CodeStore.save(0, $.SEED_QR_TITLE, $.SEED_QR_TEXT, CodeStore.TYPE_QR);
    CodeStore.save(1, $.SEED_BARCODE_TITLE, $.SEED_BARCODE_TEXT, CodeStore.TYPE_BARCODE);
    CodeStore.publishProperties();

    Test.assertEqualMessage(CodeStore.count(), 2, "two codes seeded");
    Test.assertMessage(!CodeStore.isCacheValid(0), "slot 0 starts with no image");
    Test.assertMessage(!CodeStore.isCacheValid(1), "slot 1 starts with no image");
    Test.assertMessage(!CodeGeneration.enabled(), "generation is off, so the service is the source");

    logger.debug("SEEDED 2 codes for the download fallback");
    return true;
}

(:test)
function integrationVerifyDownload(logger as Test.Logger) as Boolean {
    // Both codes downloaded, not just the first one. Before the queue existed, a single
    // in-flight flag meant every code after the first was silently dropped.
    Test.assertMessage(CodeStore.isCacheValid(0),
        "slot 0 has no valid cached image after running the app — the download never completed");
    Test.assertMessage(CodeStore.isCacheValid(1),
        "slot 1 has no valid cached image after running the app — only the first code loaded");

    // The image is attributed to the code it was generated from, so a response cannot have
    // landed on the wrong slot.
    var meta0 = Storage.getValue(CodeStore.metaTextKey(0));
    var meta1 = Storage.getValue(CodeStore.metaTextKey(1));
    // Assert presence first: calling equals on a missing key throws, and the test then reports
    // an exception rather than the failure it was written to describe.
    Test.assertMessage(meta0 instanceof String && meta1 instanceof String,
        "both slots must have cached image metadata");
    Test.assertMessage(meta0.equals($.SEED_QR_TEXT), "slot 0 image is attributed to slot 0's text");
    Test.assertMessage(meta1.equals($.SEED_BARCODE_TEXT), "slot 1 image is attributed to slot 1's text");

    var type0 = Storage.getValue(CodeStore.metaTypeKey(0)) as String;
    var type1 = Storage.getValue(CodeStore.metaTypeKey(1)) as String;
    Test.assertMessage(type0.equals(CodeStore.TYPE_QR), "slot 0 was fetched as a QR code");
    Test.assertMessage(type1.equals(CodeStore.TYPE_BARCODE), "slot 1 was fetched as a barcode");

    // A QR is square; a rectangular barcode is not. This is what actually proves the barcode
    // endpoint was used — the bug where a barcode rendered as a QR code would fail here.
    var qr = CodeStore.cachedImage(0);
    var barcode = CodeStore.cachedImage(1);
    Test.assertMessage(qr != null && barcode != null, "both bitmaps load back out of storage");

    logger.debug("QR      " + qr.getWidth() + "x" + qr.getHeight());
    logger.debug("BARCODE " + barcode.getWidth() + "x" + barcode.getHeight());

    Test.assertMessage(qr.getWidth() > 0 && qr.getHeight() > 0, "the QR bitmap has real pixels");
    Test.assertMessage(
        qr.getWidth() == qr.getHeight(),
        "a QR code should come back square, got " + qr.getWidth() + "x" + qr.getHeight());
    Test.assertMessage(
        barcode.getWidth() > barcode.getHeight(),
        "a barcode should come back wider than it is tall, got "
            + barcode.getWidth() + "x" + barcode.getHeight());

    // The glance draws from its own smaller image; it should have been fetched too.
    Test.assertMessage(CodeStore.isGlanceCacheValid(), "the glance image was fetched and cached");

    logger.debug("VERIFIED both codes downloaded, cached and correctly attributed");
    return true;
}

(:test)
function integrationVerifyNoRedownload(logger as Test.Logger) as Boolean {
    Test.assertMessage(CodeStore.isCacheValid(0), "precondition: slot 0 is cached");
    Test.assertMessage(CodeStore.isCacheValid(1), "precondition: slot 1 is cached");

    var service = ImageService.get();
    service.enqueueAll();

    Test.assertEqualMessage(service.queue.size(), 0,
        "nothing should be queued when every code already has a valid cached image");

    logger.debug("VERIFIED warm start queues no downloads");
    return true;
}

//! Issue #30, end to end: codes configured in the settings editor before the app has ever been
//! opened must survive the first launch, and `codesList` must still be something the editor can
//! save afterwards.
//!
//! The unit suite calls `Migration.run()` and `CodeStore.reconcile()` by hand. This drives the
//! real `getInitialView`, which is where the order of those two — and the wipe that used to
//! happen between them — actually lives.
(:test)
function integrationSeedIssue30(logger as Test.Logger) as Boolean {
    // A fresh install: no codes and no schema marker, so migration treats this as a first run.
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue(CodeStore.PENDING_SLOTS);
    Storage.deleteValue(Migration.SCHEMA_KEY);
    Application.Properties.setValue(CodeGeneration.SETTING, true);

    // `codesList` as the Connect IQ settings editor writes it: the three declared keys, nothing
    // else. This is step 2 of the reproduction in the issue.
    var pushed = [
        {
            "code_$index_text" => $.SEED_QR_TEXT,
            "code_$index_title" => $.SEED_QR_TITLE,
            "code_$index_type" => CodeStore.TYPE_QR
        },
        {
            "code_$index_text" => $.SEED_BARCODE_TEXT,
            "code_$index_title" => $.SEED_BARCODE_TITLE,
            "code_$index_type" => CodeStore.TYPE_BARCODE
        }
    ] as Array<Application.PropertyValueType>;
    Application.Properties.setValue(CodeStore.PROP_CODES, pushed);

    Test.assertEqualMessage(CodeStore.count(), 0, "storage starts empty, as on a fresh install");
    Test.assertEqualMessage(Migration.storedSchema(), 1, "and looks un-migrated");

    logger.debug("SEEDED 2 codes into codesList only, storage empty");
    return true;
}

(:test)
function integrationVerifyIssue30(logger as Test.Logger) as Boolean {
    // If this fails with an empty storage, check Settings > Glance Launch Mode first: in glance
    // mode `getInitialView` never runs, so the app under test never booted.
    Test.assertEqualMessage(CodeStore.count(), 2,
        "the codes configured from the phone did not survive the first launch");
    TestSupport30.assertText(0, $.SEED_QR_TEXT, "slot 0");
    TestSupport30.assertText(1, $.SEED_BARCODE_TEXT, "slot 1");
    Test.assertMessage(CodeStore.isBarcode(1), "slot 1 is still a barcode");

    // And the property the settings editor reads is still populated and still in the declared
    // shape, so step 4 of the reproduction — edit and save again — has something to work with.
    var raw = Application.Properties.getValue(CodeStore.PROP_CODES);
    Test.assertMessage(raw instanceof Array, "codesList is still an array");
    Test.assertEqualMessage((raw as Array).size(), 2, "codesList still holds both codes");
    for (var i = 0; i < (raw as Array).size(); i++) {
        var entry = (raw as Array)[i];
        Test.assertMessage(entry instanceof Dictionary, "entry " + i + " is a dictionary");
        Test.assertEqualMessage((entry as Dictionary).keys().size(), 3,
            "entry " + i + " carries only the three declared keys");
    }

    logger.debug("VERIFIED codes configured before first launch survived it, codesList intact");
    return true;
}

(:test)
module TestSupport30 {
    function assertText(slot as Number, expected as String, context as String) as Void {
        var actual = CodeStore.getText(slot);
        Test.assertMessage(actual != null && actual.equals(expected),
            context + ": expected '" + expected + "' but got '" + (actual == null ? "null" : actual) + "'");
    }
}

//! Diagnostic, not an assertion. Run it on its own when the end-to-end check fails, to see what
//! the app actually left behind:
//!
//!     monkeydo bin/integration.prg fenix7pro -t integrationDump
//!
//! A `lastError` of -101 means the simulator's phone data channel is not carrying traffic, so
//! no request could have succeeded regardless of the app.
(:test)
function integrationDump(logger as Test.Logger) as Boolean {
    logger.debug("count=" + CodeStore.count());
    for (var i = 0; i < 3; i++) {
        logger.debug("slot " + i
            + " text=" + CodeStore.getText(i)
            + " type=" + CodeStore.getType(i)
            + " cacheValid=" + CodeStore.isCacheValid(i)
            + " img=" + (Storage.getValue(CodeStore.imageKey(i)) != null)
            + " metaText=" + Storage.getValue(CodeStore.metaTextKey(i)));
    }
    logger.debug("persistedQueue=" + Storage.getValue("pendingImageSlots"));
    for (var i = 0; i < 3; i++) {
        logger.debug("slot " + i + " lastError=" + Storage.getValue(ImageService.errorKey(i)));
    }
    logger.debug("glanceError=" + Storage.getValue(ImageService.errorKey(-2)));
    logger.debug("glanceValid=" + CodeStore.isGlanceCacheValid());
    logger.debug("phoneConnected=" + System.getDeviceSettings().phoneConnected);
    return true;
}

//! Seeds two codes *with* cached images so the app renders immediately and makes no network
//! request at all. Used for visual checks of the draw path in the simulator, and it doubles as a
//! demonstration of the cache fix: a warm start shows codes with the radio never touched.
//!
//!     monkeydo bin/integration.prg fenix7pro -t integrationSeedRendered
(:test)
function integrationSeedRendered(logger as Test.Logger) as Boolean {
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue("pendingImageSlots");

    CodeStore.save(0, "Gym card", $.SEED_QR_TEXT, CodeStore.TYPE_QR);
    CodeStore.save(1, "Loyalty", $.SEED_BARCODE_TEXT, CodeStore.TYPE_BARCODE);

    var bitmap = WatchUi.loadResource(Rez.Drawables.LauncherIcon) as WatchUi.BitmapResource;
    CodeStore.putImage(0, bitmap);
    CodeStore.putImage(1, bitmap);
    CodeStore.putGlanceImage(bitmap);

    Test.assertMessage(CodeStore.isCacheValid(0), "slot 0 is cached");
    Test.assertMessage(CodeStore.isCacheValid(1), "slot 1 is cached");
    Test.assertMessage(CodeStore.isGlanceCacheValid(), "the glance is cached");

    logger.debug("SEEDED 2 codes with cached images; the app should need no network");
    return true;
}

//! Seed a barcode long enough to overflow the old layout, for a visual check that it is not
//! drawn off the edges.
//!
//!     monkeydo bin/integration.prg fenix843mm -t integrationSeedLongBarcode
(:test)
function integrationSeedLongBarcode(logger as Test.Logger) as Boolean {
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue(CodeStore.PENDING_SLOTS);
    Application.Properties.setValue(
        CodeStore.PROP_CODES, [] as Array<Application.PropertyValueType>);
    Application.Properties.setValue(CodeGeneration.SETTING, true);

    // Letters stay in Code B at 11 modules each: 18 characters is 233 modules, which with a
    // full quiet zone wanted more width than the screen has.
    CodeStore.save(0, "Long barcode", "ABCDEFGHIJKLMNOPQR", CodeStore.TYPE_BARCODE);
    CodeStore.publishProperties();

    Test.assertEqualMessage(CodeStore.count(), 1, "one long barcode seeded");
    logger.debug("SEEDED a 18-character barcode for the overflow case");
    return true;
}

//! Seed the exact payload from GitHub issue #35: a club membership barcode whose bars are too
//! thin for an older scanner to read reliably, for a visual check of how much of the display
//! width today's layout actually uses.
//!
//!     monkeydo bin/integration.prg fenix843mm -t integrationSeedIssue35Barcode
(:test)
function integrationSeedIssue35Barcode(logger as Test.Logger) as Boolean {
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue(CodeStore.PENDING_SLOTS);
    Application.Properties.setValue(
        CodeStore.PROP_CODES, [] as Array<Application.PropertyValueType>);
    Application.Properties.setValue(CodeGeneration.SETTING, true);
    // The simulator persists properties between invocations, so without this a default-mode
    // capture taken after integrationSeedIssue35BarcodeWide would silently inherit wide mode.
    Application.Properties.setValue(WideBarcode.SETTING, false);

    CodeStore.save(0, "Club card", "FFCC12345", CodeStore.TYPE_BARCODE);
    CodeStore.publishProperties();

    var bars = Code128.encode("FFCC12345");
    Test.assertMessage(bars != null, "the payload encodes");
    Test.assertMessage(!WideBarcode.enabled(), "wide mode is off for this fixture");
    Test.assertEqualMessage(CodeStore.count(), 1, "one code seeded");
    logger.debug("SEEDED issue #35 barcode: " + (bars as ByteArray).size() + " modules");
    return true;
}

//! Fill every slot up to the new MAX_CODES so Add Code can be driven by hand in the simulator to
//! see the "all slots full" confirmation that used to be a silent Log.warn.
//!
//!     monkeydo bin/integration.prg fenix843mm -t integrationSeedFullSlots
(:test)
function integrationSeedFullSlots(logger as Test.Logger) as Boolean {
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue(CodeStore.PENDING_SLOTS);
    Application.Properties.setValue(
        CodeStore.PROP_CODES, [] as Array<Application.PropertyValueType>);
    Application.Properties.setValue(CodeGeneration.SETTING, true);

    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.save(slot, "Code " + slot, "CODE-" + slot, CodeStore.TYPE_QR);
    }
    CodeStore.publishProperties();

    Test.assertEqualMessage(CodeStore.count(), CodeStore.MAX_CODES, "every slot filled");
    Test.assertEqualMessage(CodeStore.nextFreeSlot(), -1, "no free slot left");
    logger.debug("SEEDED " + CodeStore.MAX_CODES + " codes; Add Code should now refuse a new one");
    return true;
}

//! Drives the exact call a person triggers from the UI when every slot is full. Run after
//! integrationSeedFullSlots, whose 20 filled slots this depends on (simulator storage persists
//! between invocations):
//!
//!     monkeydo bin/integration.prg fenix843mm -t integrationSeedFullSlots
//!     monkeydo bin/integration.prg fenix843mm -t integrationAddCodeRefusesWhenFull
(:test)
function integrationAddCodeRefusesWhenFull(logger as Test.Logger) as Boolean {
    Test.assertEqualMessage(CodeStore.count(), CodeStore.MAX_CODES, "precondition: every slot is full");

    var menu = new AddCodeMenu(new AppView());
    menu.codeTitle = "Overflow";
    menu.codeText = "one-too-many";
    menu.codeType = CodeStore.TYPE_QR;
    menu.save();

    Test.assertEqualMessage(CodeStore.count(), CodeStore.MAX_CODES,
        "a 21st code must not be stored when every slot is full");
    logger.debug("VERIFIED: adding a code when full does not crash and does not store anything");
    return true;
}

//! Same payload as integrationSeedIssue35Barcode, with wide mode already on -- for a matched
//! before/after screenshot pair.
//!
//!     monkeydo bin/integration.prg fenix843mm -t integrationSeedIssue35BarcodeWide
(:test)
function integrationSeedIssue35BarcodeWide(logger as Test.Logger) as Boolean {
    for (var slot = 0; slot < CodeStore.MAX_CODES; slot++) {
        CodeStore.deleteSlot(slot);
    }
    Storage.deleteValue(CodeStore.PENDING_SLOTS);
    Application.Properties.setValue(
        CodeStore.PROP_CODES, [] as Array<Application.PropertyValueType>);
    Application.Properties.setValue(CodeGeneration.SETTING, true);
    Application.Properties.setValue(WideBarcode.SETTING, true);

    CodeStore.save(0, "Club card", "FFCC12345", CodeStore.TYPE_BARCODE);
    CodeStore.publishProperties();

    Test.assertMessage(WideBarcode.enabled(), "wide mode is on for this fixture");
    Test.assertEqualMessage(CodeStore.count(), 1, "one code seeded");
    logger.debug("SEEDED issue #35 barcode with wide mode on");
    return true;
}
