name: Build Garmin App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matco/connectiq-tester:v2.3.0
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup developer key
        env:
          DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
        run: |
          echo "$DEVELOPER_KEY" > developer_key.der

      - name: Build Debug
        run: |
          monkeyc -o bin/garmin-qr.prg -y developer_key.der -d fenix7pro -w -f monkey.jungle

      - name: Build Release
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          monkeyc -o bin/garmin-qr.prg -y developer_key.der -d fenix7pro -r -f monkey.jungle

      - name: Upload Debug Build
        uses: actions/upload-artifact@v4
        with:
          name: debug-build
          path: bin/garmin-qr.prg
          if-no-files-found: error

      - name: Upload Release Build
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: bin/garmin-qr.prg
          if-no-files-found: error 